import BackToTop from "@/components/BackToTop";
import SocialMediaSidebar from "@/components/SocialMediaSidebar";
import AuthHeader from "@/layouts/auth/MainHeader";

export const metadata = {
  title: "Abroad Inquiry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* <AuthHeader /> */}
      {children}
      <SocialMediaSidebar />
      <BackToTop />
    </>
  );
}
