// slick-carousel
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
// scroll bar
import "simplebar-react/dist/simplebar.min.css";

import NotistackProvider from "@/components/NotistackProvider";
import MotionLazyContainer from "@/components/animate/MotionLazyContainer";
import { defaultSettings } from "@/config";
import { SettingsProvider } from "@/contexts/SettingsContext";
import ThemeProvider from "@/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Providers } from '../redux/provider';
import { store } from "@/redux/store";

import { cookies } from "next/headers";

export const metadata = {
  title: "Abroad Inquiry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookiesValue = cookies()
    .getAll()
    .reduce((acc, cookie) => {
      acc[cookie.name] = cookie.value || defaultSettings[cookie.name];
      return acc;
    }, {});

  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <SettingsProvider defaultSettings={cookiesValue}>
            <ThemeProvider>
              <NotistackProvider>
                <MotionLazyContainer>
                 <Providers store={store}>
                  {children}
                  </Providers>
                  </MotionLazyContainer>
              </NotistackProvider>
            </ThemeProvider>
          </SettingsProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
